version: "3.9"

services:
  server:
    container_name: kaupunginosat
    image: "kaupunginosat"
    ports: ["3000:3000"]
    links:
      - "db:redis"
  db:
    container_name: redis
    image: redis/redis-stack-server
  nginx:
    container_name: districts-nginx
    image: lscr.io/linuxserver/nginx
    volumes:
      - /srv/podman/kaupunginosat/nginx:/config
    ports: ["3001:80"]
    links:
      - "server:kaupunginosat"
